apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: db_faraday
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: F4r4d4y4lt0
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-faraday-volume
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/var/lib/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-faraday-claim
  labels:
    app: postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: faraday-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: faraday-postgres
  template:
    metadata:
      labels:
        app: faraday-postgres
    spec:
      containers:
        - name: faraday-postgres
          image: postgres:10.1
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-faraday-claim
---
piVersion: v1
kind: Service
metadata:
  name: faraday-postgres
  labels:
    app: faraday-postgres
spec:
  type: NodePort
  ports:
   - port: 5432
  selector:
   app: faraday-postgres
